name: preview_on_pr_update
# only run when updating an 'Open' PR  # retry fix

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Simple test job to verify PR and draft conditions
  test-pr-conditions:
    if: github.event.pull_request.state == 'open' && !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Status
        run: |
          echo "✅ PR Condition Check Passed!"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR State: ${{ github.event.pull_request.state }}"
          echo "PR Draft: ${{ github.event.pull_request.draft }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
          
      - name: Simulate Success
        run: |
          echo "🎉 This job only runs for non-draft, open PRs"
          echo "If you see this message, the conditions are working correctly!"
